- name: Configure VLANs on Cisco Switch
  hosts: cisco
  gather_facts: no

  vars_files:
    - vars/vlans.yml

  tasks:
    - name: Preview VLAN config (Jinja2 template to text file)
      template:
        src: template/vlantemplate2.j2
        dest: /tmp/vlan_config_preview.txt
      delegate_to: localhost

    - name: Apply VLAN configuration
      cisco.ios.ios_vlans:
        config: "{{ vlans }}"
