- name: Configure VLANs on Cisco Switch
  hosts: cisco
  gather_facts: no
  connection: network_cli

  vars_files:
    - vars/vlans.yml

  tasks:
    - name: Preview VLAN config (Jinja2 template to text file)
      template:
        src: template/vlanstemplate.j2         # ✅ matches your folder
        dest: template/vlan_config_preview.txt    # ✅ safe destination

    - name: Apply VLAN configuration
      cisco.ios.ios_vlans:
        config: "{{ vlans }}"
